### ISSUE TITLE
[Gene Page] Setup gene page sections to consume API endpoints on LIVE

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc-mousephenotype-web#18]
- [x] Add logic and environment variables to make the local run point to the mock data service and the LIVE run to point to the different endpoints
- [x] Gene summary section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1929293/summary
- [x] Gene expression section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1929293/expression
- [x] Gene order section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1929293/order
- [x] Gene diseases section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1929293/disease
- [x] Gene publications section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1860086/publication
- [x] Allele products page points to: https://nginx.mousephenotype-dev.org/api/v1/alleles/MGI:1929293/tm1a(EUCOMM)Wtsi
- [x] Gene stats results section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1860086/statistical-result
- [x] Histopathology section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:2143539/histopathology
- [x] Gene Phenotype Hits section points to: https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:1929293/phenotype-hits
- [x] Gene Images points to https://nginx.mousephenotype-dev.org/api/v1/genes/MGI:2444773/images

**Comment by johnnyluu** [comment]
The env is already there: NEXT_PUBLIC_API_MOCKING=enabled. I've removed it from the production env

**Comment by rwilson-ebi** [comment]
Osman has updated the mock data in all the backend services.
