### ISSUE TITLE
[Chart pages] Research behaviour of IPGTT chart pages

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc-mousephenotype-web#197]
Research behaviour of IPGTT chart pages: https://www.mousephenotype.org/data/charts?accession=MGI:1929293&allele_accession_id=MGI:5548707&pipeline_stable_id=HRWL_001&procedure_stable_id=IMPC_IPG_001&parameter_stable_id=IMPC_IPG_002_001&zygosity=homozygote&phenotyping_center=MRC%20Harwell

Seems like IPGTT not only shows the time series chart for also all the derived parameters:

see: https://github.com/mpi2/PhenotypeData/blob/056aba5041049715c3be9c2910f206edaa8ef029/web/src/main/java/uk/ac/ebi/phenotype/chart/GraphUtils.java#L172

**Comment by francisco-ebi** [comment]
@ficolo I have seen that only if you open the chart page for this parameter : IMPC_IPG_002_001 will show the rest of the parameters, like in [this example](https://www.mousephenotype.org/data/charts?accession=MGI:1929293&allele_accession_id=MGI:5548707&pipeline_stable_id=HRWL_001&procedure_stable_id=IMPC_IPG_001&parameter_stable_id=IMPC_IPG_002_001&zygosity=homozygote&phenotyping_center=MRC%20Harwell).

This [other link](https://www.mousephenotype.org/data/charts?accession=MGI:1929293&allele_accession_id=MGI:5548707&pipeline_stable_id=HRWL_001&procedure_stable_id=IMPC_IPG_001&parameter_stable_id=IMPC_IPG_012_001&zygosity=homozygote&phenotyping_center=MRC%20Harwell) is for the same gene but a derived parameter and its going to show only one chart.

The list is handled by this constant: 
`public static final List<String> IMPC_IPG_002_001 = Arrays.asList(
            "IMPC_IPG_012_001", "IMPC_IPG_011_001", "IMPC_IPG_010_001");`

I have created the PR for the chart and I have changed the behaviour so whenever you open a chart that has the procedureStableId equal to IMPC_IPG_001, it's going to fetch all the parameters.
