### ISSUE TITLE
[GENE] Phenotype system Icons component

### ISSUE THREAD

**Issue by ficolo** [mpi2/impc-mousephenotype-web#6]
The goal of this component is to inform the user what the status of the phenotyping process for a given gene, currently we only use it on the Gene Page, but we would like to re use it in other pages, like the Search page.

The grid is formed by a group of "Physiological system" which are set of top level terms in the Mammalian Phenotype Ontology.

The corresponding icon for a _Physiological system_ should light up with a color when there is a significant hit or any of the Ontology terms that belong to said _Physiological system_, a different color if the phenotyping process has been performed and has return a not significant result and it should appear disabled if the gene hasn't been tested for any of the _Physiological system_ phenotypes.

![Screenshot 2022-01-26 at 21 49 45](https://user-images.githubusercontent.com/2343039/151252766-7e84dbeb-f7a6-4037-af75-3b7f172402d5.png)

You can change the icons, most of them come from FontAwesome, but the embryo icon we made ourselves, after some discussions with our stakeholders, this actually depicts a mouse embryonic stage, so that one probably should stay similar to the current one, the icons have been always a difficult topics, considering they are abstractions of physiological systems, some of them not easily translatable to icons.

**Comment by johnnyluu** [comment]
@ficolo Do you have a list of all the values?

**Comment by ficolo** [comment]
| Physiological system                                                  | Icon CSS class                   |
|-----------------------------------------------------------------------|----------------------------------|
| "mortality/aging":                                                    |        "fas fa-skull-crossbones" |
| "embryo phenotype":                                                   | "impc-embryo"                    |
| "reproductive system   phenotype":                                    | "impc-sperm"                     |
| "growth/size/body region   phenotype":                                | "fas fa-balance-scale-right"     |
| "homeostasis/metabolism   phenotype or adipose tissue phenotype":     | "fas fa-bolt"                    |
| "behavior/neurological   phenotype or nervous system phenotype":      | "fas fa-brain"                   |
| "cardiovascular system   phenotype":                                  | "fas fa-heart"                   |
| "respiratory system   phenotype":                                     | "fas fa-lungs"                   |
| "digestive/alimentary   phenotype or liver/biliary system phenotype": | "fas fa-stomach"                 |
| "renal/urinary system   phenotype":                                   | "fas fa-kidneys"                 |
| "limbs/digits/tail   phenotype":                                      | "fas fa-hand-paper"              |
| "skeleton   phenotype":                                               | "fas fa-bone"                    |
| "immune system phenotype   or hematopoietic system phenotype":        | "fas fa-tint"                    |
| "muscle phenotype":                                                   | "fas fa-dumbbell"                |
| "integument phenotype or   pigmentation phenotype":                   | "fas fa-diagnoses"               |
| "craniofacial   phenotype":                                           | "fas fa-meh"                     |
| "hearing/vestibular/ear   phenotype":                                 | "fas fa-ear"                     |
| "taste/olfaction   phenotype":                                        | "impc-nose"                      |
| "endocrine/exocrine gland   phenotype":                               | "impc-trachea"                   |
| "vision/eye   phenotype":                                             | "fas fa-eye"                     |
